# Spring ??
spring:
  web:
    locale: ko_KR
    resources:
      add-mappings: false
  messages:
    basename: message/messages
  # 404(Not Found) ?? ? throw ??? ???
  mvc:
    throw-exception-if-no-handler-found: true